### ISSUE TITLE
Ревью кода

### ISSUE THREAD

**Issue by kanny4uHo** [DbnStr/Android-Project-2020-Z_Team#41]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/AuthViewModel.java#L17
Может запилить здесь просто enum со значениями различных стейтов?

**Comment by RyzhkovNikita** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/AuthViewModel.java#L22
здесь вроде прям MediatorLiveData не нужна, можно заменить на mutableLiveData

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/AuthViewModel.java#L22
довольно хитро сделали) молодцы, придумали
на слое выше, чем слой представления, лучше не юзать livedata. Лучше заюзать обычные коллбэки или rx

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/MainMenuActivity.java#L40
можно запилить поля приватными

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/MainMenuActivity.java#L49
а чего не через Логгер?)

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/MainActivity.java#L13
везде все, что можно сделать приватным, стоить сделать приватным

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/LoginActivity.java#L44
можно объединить с объявлением

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/LoginActivity.java#L63
здесь тоже лучше заменить на enum

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/LoginActivity.java#L81
что нибудь вроде enum AuthState { SUCCESS, FAILED }
как у вас сделано в AuthRepository

**Comment by kanny4uHo** [comment]
зарегался и перешел на последнюю вкладку
Process: ru.mail.z_team, PID: 28555
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at ru.mail.z_team.icon_fragments.profile.ProfileRepository.lambda$addUserInLocalDB$0$ProfileRepository(ProfileRepository.java:101)
        at ru.mail.z_team.icon_fragments.profile.-$$Lambda$ProfileRepository$IW7GBw6xxGPiQti23pKen8okqO0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/user/User.java#L72
рефлексия - это сильно
если можно обойтись без нее, лучше обойтись без нее
вы передаете сюда иинформацию, которую пользователь может менять из UI
заведите модельку UserInfoUi с редактируемыми полями, которую вы будете создавать выше и прокидывать сюда

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/user/UserFragment.java#L95
unused

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/map/MapViewModel.java#L28
молодцы, что разделили методы комментариями для каждого фрагмента
создайте реально 2 разных вью модели

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/map/MapActivity.java#L22
с точки зрения проектирования использование активити как общего хоста - как-то не очень
попробуйте сделать идею, как примерно здесь описано
https://habr.com/ru/post/504712/

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/map/MapActivity.java#L56
проверять пермишн конечно полезно, но если я сверну и отберу у приложения разрешение вручную, onCreate уже не вызовется, и я попаду на мап фрагмент

**Comment by kanny4uHo** [comment]
чекайте все warnings (желтые замечания от студии), все нужно исправлять

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/walks/StoryFragment.java#L58
тоже через логгер можно

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/walks/StoryFragment.java#L52
строки-ключи удобно выносить в константы

**Comment by kanny4uHo** [comment]
![image](https://user-images.githubusercontent.com/47972690/103036026-c1d12280-4579-11eb-8868-b55109a518d1.png)
плюсик чет плывет, наверно так быть не должно)

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/profile/ProfileFragment.java#L108
можно внести вызов этого метода в конструктор вью модели, так не будет вызывать апдейт каждый раз при повороте

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/news/NewsAdapter.java#L57
в целом это простое нормальное решение, если не менять больше ничего и никогда)
по-хорошему, сюда нужно прокидывать какой-то листенер из фрагмента, который при клике будет дергать адаптер. Затем фрагмент дернет вью модель, а та уже решит, что делать. Если нужно открыть какой-то экран, вью модель дернет какой-то навигатор, интерфейс которого может реализовать активити

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/friends/friend_request/FriendRequestFragment.java#L64
дублирование

**Comment by kanny4uHo** [comment]
https://github.com/DbnStr/Android-Project-2020-Z_Team/blob/4bcae71dc71cf3dee1ef9d68fd6843e71bbfd91c/app/src/main/java/ru/mail/z_team/icon_fragments/friends/friend_request/FriendRequestFragment.java#L74
по аналогии с комментом выше, можно внести в конструктор вью модели
